services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend
  lab301:
    container_name: lab301
    image: lab301:v0.1
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
